# Generated by Django 6.1.1 on 2026-09-27 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=50, unique=True)),
                ('motivo', models.TextField()),
                ('puntos', models.DecimalField(decimal_places=2, default=-1.0, max_digits=5)),
                ('estado', models.CharField(choices=[('creado', 'Expediente Creado'), ('justificando', 'En período de justificaciones'), ('revision_resolucion', 'Justificaciones en revisión'), ('espera_resolucion', 'Espera de resolución'), ('pendiente_correos', 'Pendiente de correos'), ('emitido', 'Expedientes ya emitidos')], db_index=True, default='creado', max_length=30)),
                ('plazo_inicio_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp inmutable de notificación/apertura del acuse de sanción (S2-04).', null=True)),
                ('plazo_limite_at', models.DateTimeField(blank=True, db_index=True, help_text='Deadline congelado computado en días hábiles.', null=True)),
                ('descargo_presentado', models.BooleanField(db_index=True, default=False, help_text='Indica si el socio ya presentó su descargo reglamentario.')),
                ('descargo_tipo', models.CharField(blank=True, choices=[('T02_CERTIFICADO', 'Formulario T02 - Causal con Certificado'), ('T03_EXTRAORDINARIO', 'Formulario T03 - Extraordinario')], max_length=30, null=True)),
                ('descargo_causal', models.CharField(blank=True, max_length=255, null=True)),
                ('descargo_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('descargo_texto', models.TextField(blank=True, null=True)),
                ('descargo_presentado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Expediente Disciplinario',
                'verbose_name_plural': 'Expedientes Disciplinarios',
                'db_table': 'expedientes_expediente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CambioEstadoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('creado', 'Expediente Creado'), ('justificando', 'En período de justificaciones'), ('revision_resolucion', 'Justificaciones en revisión'), ('espera_resolucion', 'Espera de resolución'), ('pendiente_correos', 'Pendiente de correos'), ('emitido', 'Expedientes ya emitidos')], max_length=30)),
                ('estado_nuevo', models.CharField(choices=[('creado', 'Expediente Creado'), ('justificando', 'En período de justificaciones'), ('revision_resolucion', 'Justificaciones en revisión'), ('espera_resolucion', 'Espera de resolución'), ('pendiente_correos', 'Pendiente de correos'), ('emitido', 'Expedientes ya emitidos')], max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.CharField(default='SISTEMA', help_text='Usuario, rol o job responsable de la transición.', max_length=150)),
                ('motivo', models.TextField(blank=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'Cambio de Estado de Expediente',
                'verbose_name_plural': 'Cambios de Estado de Expedientes',
                'db_table': 'expedientes_cambio_estado',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
