# Generated by Django 4.2.30 on 2026-10-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudt01',
            name='razon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='solicitudt01',
            name='reglamentos_respaldantes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='solicitudt01',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
