# Generated by Django 4.2.30 on 2026-10-01 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudT01',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitido')], default='DRAFT', max_length=10)),
                ('destinatario_socio_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tipo_accion', models.CharField(choices=[('SANCTION', 'Sanción'), ('MERIT', 'Mérito')], max_length=10)),
                ('causal', models.CharField(blank=True, max_length=255)),
                ('puntos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('anexo_fecha', models.DateField(blank=True, null=True)),
                ('anexo_lugar', models.CharField(blank=True, max_length=255)),
                ('anexo_relato', models.TextField(blank=True)),
                ('anexo_testigos', models.TextField(blank=True)),
                ('snapshot_destinatario', models.JSONField(blank=True, null=True)),
                ('snapshot_emitido', models.JSONField(blank=True, null=True)),
                ('numero_expediente', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socios.socio')),
            ],
        ),
    ]
