# Generated by Django 4.2.16 on 2026-10-04 21:10

from django.db import migrations, models
import django.db.models.deletion
import re

NUMERO_PATTERN = re.compile(r"^EXP-(\d+)$")


def link_existing_socios(apps, schema_editor):
    """Incorpora el socio principal de cada expediente existente a la colección `socios`."""
    Expediente = apps.get_model("expedientes", "Expediente")
    for expediente in Expediente.objects.all().iterator():
        expediente.socios.add(expediente.socio_id)


def seed_number_sequence(apps, schema_editor):
    """Arranca el contador después del mayor número `EXP-NNNNNN` ya emitido."""
    Expediente = apps.get_model("expedientes", "Expediente")
    ExpedienteNumberSequence = apps.get_model("expedientes", "ExpedienteNumberSequence")
    last_value = max(
        (
            int(match.group(1))
            for numero in Expediente.objects.values_list("numero", flat=True)
            if (match := NUMERO_PATTERN.match(numero))
        ),
        default=0,
    )
    ExpedienteNumberSequence.objects.update_or_create(pk=1, defaults={"last_value": last_value})


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'expedientes_numero_secuencia',
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='socios',
            field=models.ManyToManyField(blank=True, related_name='expedientes_implicados', to='socios.socio'),
        ),
        migrations.AlterField(
            model_name='cambioestadoexpediente',
            name='estado_anterior',
            field=models.CharField(choices=[('creado', 'Expediente Creado'), ('justificando', 'En período de justificaciones'), ('revision_resolucion', 'Justificaciones en revisión'), ('espera_resolucion', 'En espera de resolución'), ('pendiente_correos', 'Pendiente de firma y envío'), ('emitido', 'Expedientes ya emitidos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cambioestadoexpediente',
            name='estado_nuevo',
            field=models.CharField(choices=[('creado', 'Expediente Creado'), ('justificando', 'En período de justificaciones'), ('revision_resolucion', 'Justificaciones en revisión'), ('espera_resolucion', 'En espera de resolución'), ('pendiente_correos', 'Pendiente de firma y envío'), ('emitido', 'Expedientes ya emitidos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('creado', 'Expediente Creado'), ('justificando', 'En período de justificaciones'), ('revision_resolucion', 'Justificaciones en revisión'), ('espera_resolucion', 'En espera de resolución'), ('pendiente_correos', 'Pendiente de firma y envío'), ('emitido', 'Expedientes ya emitidos')], db_index=True, default='creado', max_length=30),
        ),
        migrations.CreateModel(
            name='DescargoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T02_CERTIFICADO', 'Formulario T02 - Causal con Certificado'), ('T03_EXTRAORDINARIO', 'Formulario T03 - Extraordinario')], max_length=30)),
                ('causal', models.CharField(blank=True, max_length=255)),
                ('archivo', models.CharField(blank=True, max_length=255)),
                ('texto', models.TextField(blank=True)),
                ('presentado_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargos', to='expedientes.expediente')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descargos_expedientes', to='socios.socio')),
            ],
            options={
                'db_table': 'expedientes_descargo',
            },
        ),
        migrations.AddConstraint(
            model_name='descargoexpediente',
            constraint=models.UniqueConstraint(fields=('expediente', 'socio'), name='unique_descargo_per_expediente_socio'),
        ),
        migrations.RunPython(link_existing_socios, migrations.RunPython.noop),
        migrations.RunPython(seed_number_sequence, migrations.RunPython.noop),
    ]
