# Generated by Django 4.2.30 on 2026-10-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_solicitudt01_razon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudt01',
            name='destinatarios_socios_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='solicitudt01',
            name='snapshots_destinatarios',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
