# Generated by Django 4.2.30 on 2026-10-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_expediente_trazabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudt01',
            name='expediente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_t01', to='expedientes.expediente'),
        ),
    ]
