# Generated by Django 4.2.30 on 2026-10-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_solicitudt01_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='urgencia',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('urgente', 'Urgente')], db_index=True, default='normal', help_text='Nivel de urgencia procesal (Baja, Normal, Urgente).', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudt01',
            name='urgencia',
            field=models.CharField(blank=True, choices=[('baja', 'Baja'), ('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=20),
        ),
    ]
