# Generated by Django 4.2.30 on 2026-10-08 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedientes', '0006_solicitudt01_expediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(db_index=True, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('vigencia_desde', models.DateField(db_index=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('motivo_cambio', models.TextField(help_text='Justificación formal de auditoría para la creación/modificación de la versión.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendarios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de Calendario Institucional',
                'verbose_name_plural': 'Versiones de Calendario Institucional',
                'db_table': 'expedientes_calendario_version',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='FeriadoExcepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Feriado Nacional'), ('PROVINCIAL', 'Feriado Provincial'), ('INSTITUCIONAL', 'Asueto Institucional'), ('EXCEPCION', 'Día Inhábil Excepcional')], default='NACIONAL', max_length=30)),
                ('es_laborable', models.BooleanField(default=False, help_text='False indica día inhábil (feriado/asueto); True para excepciones laborables.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendario_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='expedientes.calendarioversion')),
            ],
            options={
                'verbose_name': 'Feriado o Excepción de Calendario',
                'verbose_name_plural': 'Feriados y Excepciones de Calendario',
                'db_table': 'expedientes_feriado_excepcion',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='calendario_version',
            field=models.ForeignKey(blank=True, help_text='Versión del calendario institucional aplicada al congelar el plazo (CA3).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_congelados', to='expedientes.calendarioversion'),
        ),
        migrations.AddConstraint(
            model_name='feriadoexcepcion',
            constraint=models.UniqueConstraint(fields=('calendario_version', 'fecha'), name='unique_fecha_per_calendario_version'),
        ),
    ]
