# Generated by Django 4.2.30 on 2026-10-10 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expedientes", "0008_seed_calendario_2026"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("USER", "Registro por usuario"),
                            ("SYSTEM", "Carga inicial del sistema"),
                            ("LEGACY", "Registro previo sin autoría registrada"),
                        ],
                        default="USER",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institutional_holidays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feriado institucional",
                "verbose_name_plural": "Feriados institucionales",
                "db_table": "expedientes_institutional_holiday",
                "ordering": ["date"],
            },
        ),
        migrations.AddConstraint(
            model_name="holiday",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("created_by__isnull", False), ("origin", "USER")),
                    models.Q(("created_by__isnull", True), ("origin__in", ["SYSTEM", "LEGACY"])),
                    _connector="OR",
                ),
                name="holiday_requires_creation_audit",
            ),
        ),
    ]
