# Generated by Django 4.2.30 on 2026-09-26 00:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to', models.JSONField(help_text='Lista de direcciones de correo destinatarias principales.')),
                ('cc', models.JSONField(blank=True, default=list, help_text='Lista de direcciones de correo en copia.')),
                ('bcc', models.JSONField(blank=True, default=list, help_text='Lista de direcciones de correo en copia oculta.')),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(help_text='Contenido del mensaje en texto plano.')),
                ('body_html', models.TextField(blank=True, help_text='Contenido opcional del mensaje formateado en HTML.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de envío o reintento'), ('SENT', 'Despachado exitosamente'), ('FAILED', 'Falló tras agotar reintentos')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadatos contextuales para auditoría y trazabilidad.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mensaje Outbox',
                'verbose_name_plural': 'Mensajes Outbox',
                'db_table': 'notifications_email_outbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_base64', models.TextField(help_text='Contenido binario codificado en Base64.')),
                ('mimetype', models.CharField(default='application/octet-stream', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.emailoutbox')),
            ],
            options={
                'verbose_name': 'Adjunto de Notificación',
                'verbose_name_plural': 'Adjuntos de Notificaciones',
                'db_table': 'notifications_email_attachment',
            },
        ),
    ]
