# Generated by Django 4.2.16 on 2026-09-16 23:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcomision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Subcomisión',
                'verbose_name_plural': 'Subcomisiones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('social_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('category', models.CharField(choices=[('PASSIVE', 'Pasivo'), ('ACTIVE', 'Activo')], max_length=10)),
                ('role', models.CharField(choices=[('SOCIO', 'Socio Ordinario'), ('FISCALIZADORA', 'Autoridad de Subcomisión / Líder de Equipo'), ('CD', 'Comisión Directiva'), ('TD', 'Tribunal de Disciplina'), ('ADMIN', 'Administrador de Cómputos')], db_index=True, default='SOCIO', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('subcomision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='socios.subcomision')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
