# Generated by Django 4.2.30 on 2026-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeAplicado',
            fields=[
                ('idPuntajeAplicado', models.AutoField(db_column='idPuntajeAplicado', primary_key=True, serialize=False)),
                ('puntajeAplicado', models.DecimalField(db_column='puntajeAplicado', decimal_places=2, max_digits=10)),
                ('expediente_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Puntaje Aplicado (Libro Mayor)',
                'verbose_name_plural': 'Puntajes Aplicados (Libro Mayor)',
                'db_table': 'tribunal_puntajeaplicado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntajeGeneral',
            fields=[
                ('idPuntajeGeneral', models.AutoField(db_column='idPuntajeGeneral', primary_key=True, serialize=False)),
                ('puntos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('felicitaciones', models.IntegerField(default=0)),
                ('llamadosAtencion', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Puntaje General (Caché)',
                'verbose_name_plural': 'Puntajes Generales (Caché)',
                'db_table': 'tribunal_puntajegeneral',
                'managed': False,
            },
        ),
    ]
