# Generated by Django 4.2.30 on 2026-09-16 02:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSocio',
            fields=[
                ('codEstadoSocio', models.AutoField(db_column='codEstadoSocio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Socio',
                'verbose_name_plural': 'Estados de Socio',
                'db_table': 'socio_estado',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('nroSocio', models.AutoField(db_column='nroSocio', primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('fechaIngreso', models.DateField(default=datetime.date.today)),
                ('codTipoDoc', models.IntegerField(default=1)),
                ('nroDoc', models.IntegerField(default=0)),
                ('fechaNac', models.DateField(blank=True, null=True)),
                ('codSexo', models.IntegerField(default=1)),
                ('codEstadoCivil', models.IntegerField(blank=True, null=True)),
                ('fechaBaja', models.DateField(blank=True, null=True)),
                ('anoSocial', models.IntegerField(default=1)),
                ('ingresante', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('forzarCambioClave', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'socio_lista',
            },
        ),
        migrations.CreateModel(
            name='Subcomision',
            fields=[
                ('codSubcomision', models.AutoField(db_column='codSubcomision', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Subcomisión',
                'verbose_name_plural': 'Subcomisiones',
                'db_table': 'socio_tiposubcomision',
            },
        ),
        migrations.CreateModel(
            name='TipoSocio',
            fields=[
                ('idTipoSocio', models.AutoField(db_column='idTipoSocio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de Socio',
                'verbose_name_plural': 'Tipos de Socio',
                'db_table': 'socio_tipoSocio',
            },
        ),
        migrations.CreateModel(
            name='SocioEstudio',
            fields=[
                ('compositeKey', models.IntegerField(db_column='compositeKey', primary_key=True, serialize=False)),
                ('nroLegajo', models.IntegerField(db_column='nroLegajo')),
                ('codEspecialidad', models.IntegerField(default=1)),
                ('curso', models.CharField(blank=True, max_length=10, null=True)),
                ('aula', models.CharField(blank=True, max_length=10, null=True)),
                ('codTurno', models.IntegerField(blank=True, null=True)),
                ('socio', models.ForeignKey(db_column='nroSocio', on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='ranking.socio')),
            ],
            options={
                'verbose_name': 'Estudio de Socio',
                'verbose_name_plural': 'Estudios de Socio',
                'db_table': 'socio_estudio',
            },
        ),
        migrations.AddField(
            model_name='socio',
            name='subcomision',
            field=models.ForeignKey(blank=True, db_column='codSubcomision', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='socios', to='ranking.subcomision'),
        ),
        migrations.AddField(
            model_name='socio',
            name='tipoSocio',
            field=models.ForeignKey(blank=True, db_column='idTipoSocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='socios', to='ranking.tiposocio'),
        ),
        migrations.CreateModel(
            name='PuntajeGeneral',
            fields=[
                ('idPuntajeGeneral', models.AutoField(db_column='idPuntajeGeneral', primary_key=True, serialize=False)),
                ('puntos', models.FloatField(default=0.0)),
                ('felicitaciones', models.IntegerField(default=0)),
                ('llamadosAtencion', models.IntegerField(default=0)),
                ('socio', models.OneToOneField(db_column='socio_id', on_delete=django.db.models.deletion.CASCADE, related_name='puntaje_general', to='ranking.socio')),
            ],
            options={
                'verbose_name': 'Puntaje General (Caché)',
                'verbose_name_plural': 'Puntajes Generales (Caché)',
                'db_table': 'tribunal_puntajegeneral',
            },
        ),
        migrations.CreateModel(
            name='PuntajeAplicado',
            fields=[
                ('idPuntajeAplicado', models.AutoField(db_column='idPuntajeAplicado', primary_key=True, serialize=False)),
                ('puntajeAplicado', models.FloatField(db_column='puntajeAplicado')),
                ('expediente_id', models.IntegerField(blank=True, null=True)),
                ('socio', models.ForeignKey(db_column='socio_id', on_delete=django.db.models.deletion.CASCADE, related_name='puntajes_aplicados', to='ranking.socio')),
            ],
            options={
                'verbose_name': 'Puntaje Aplicado (Libro Mayor)',
                'verbose_name_plural': 'Puntajes Aplicados (Libro Mayor)',
                'db_table': 'tribunal_puntajeaplicado',
            },
        ),
    ]
