# Generated by Django 4.2.30 on 2026-09-16 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fechaNac',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
