# Generated by Django 4.2.30 on 2026-09-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_alter_socio_fechanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntajeaplicado',
            name='puntajeAplicado',
            field=models.DecimalField(db_column='puntajeAplicado', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='puntajegeneral',
            name='puntos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
